version = 1

[global]
no_fp16 = false

[[game]]
exe = "BlackOps4.exe"
multiplier = 3
flow_scale = 1.0
performance_mode = true
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "GTAIV.exe"
multiplier = 2
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "GameThread"
multiplier = 3
flow_scale = 1.0
performance_mode = true
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "LibertyCity.exe"
multiplier = 2
flow_scale = 1.0
performance_mode = true
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "Main"
multiplier = 1
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "SanAndreas.exe"
multiplier = 3
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "ViceCity.exe"
multiplier = 2
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "benchmark"
multiplier = 4
flow_scale = 1.0
performance_mode = true
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "speed.exe"
multiplier = 2
flow_scale = 1.0
performance_mode = true
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "vkcube"
multiplier = 4
flow_scale = 0.7
performance_mode = true
hdr_mode = false
experimental_present_mode = "fifo"
