version = 2

[global]
allow_fp16 = true
dll = "/home/anas/.steam/steam/steamapps/common/Lossless Scaling/Lossless.dll"

[[profile]]
flow_scale = 1.0
multiplier = 4
name = "4x FG / 85% [Performance]"
pacing = "none"
performance_mode = false

[[profile]]
active_in = "Main"
flow_scale = 1.0
multiplier = 2
name = "2x FG / 100%"
pacing = "none"
performance_mode = false
